### ISSUE TITLE
"Gift has already been claimed"

### ISSUE THREAD

**Issue by volumika** [brendeni1/Nitro-Generator#4]
Links generate successfully, however upon visiting these links, disclosure for the Nitro itself is blank and when redeemed, believes that it has already been claimed.

Can be reproduced here:
 https://discord.com/billing/partner-promotions/1180231712274387115/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..sBPfcdJdlkKGQYLw.4fjOPD5qWRitr30ZhBGvwr8ffEjPZvwjuqkD1DNmFFjlUiKMm_WHKPNrEDfRFCvMvHDYsjuQBCiojS7mNnOxhBadjFUQjaGY6XnT_iCDx7CfpCzch3ZI_64s1E2pTsd-eZcBdQ3-O2NKifzFyOQ31xE6v-7sZPWEVrcsvfBfHfJWNjyTZKnSXoAd-gep5gFUeTyzblQUlSdhDk9P7Q5eXN2RrSfszU4-WA1LNv8SwRp8hujLElHY2GEtd0aC3med_YOg7tvYO1mnISYYXF7tdvQ.LGicn2rKzyyN_j-2TM62SA

https://discord.com/billing/partner-promotions/1180231712274387115/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..IPWe79QAZsTI0bvC.h8yP_MIsvc4hELWuBP2hVfFsviewkii-nfzeYEoPfGv08hf-4T4CeBYiC-olVAqv3SP2CtF5BOEm8ww_KSywvosH4QZXiOqN7zJQQHrCcmcqyExkup2n83hfSjO0zmLQYtCZhcFTbsPMzOY-HoKFolqC4L1HCfe548quRyVfxGNMl6DLIImhA-eOFD4FItFju_rHOMHIXVSFfWOpTm-qq72OyILPO9WiMNJrJhuvBcNiRD2oBowDNgsCN4d69LYqWSMfxLrWsw-hc4eFFvtfDLU.ZLmHFbcy6QLb5fU08ZUBoA

https://discord.com/billing/partner-promotions/1180231712274387115/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..v3v_h3z2rIuOuRoN.9pA8qGLw0IrkszDfeg-m_5Ju2aiXVRLW-gERzn1CU_IVQt39g7eOEm5WxZ5pekI-ljm1enT9nYoWEldmpzK4tN9Sz-NQqAvy_82gHymlGWP6RYrRNaCBJr40ed_6a4DFM0skyN_EhlZIdsZg1BmDK13lPIA7hJSY2E7QovFT_Tmp9yRNyQWn0skUWUiquewVxqrj_Ss71suljzm4bXIlAxIjg9mGlPD0hpwecBQYJ7w4KIzDgUaSZfFSZCRTJlgS7_60_kSsbehQ0gp64QL0BJU.8_3hiYN_YXDb4tBofXSegw

 https://discord.com/billing/partner-promotions/1180231712274387115/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..B8IQI5stILnL44jJ.M8Afx8ry4MpH1o6ijP3RBIEzC75427SE8JB2Emp3friXCJSHpUq0IZ23o_sk0n_yuJ7CCa5b3C9AAiYSWGJYDOuglEOcEepct0rzu1-X2n8kBDQdUcsOj7VClbVqQU0c2XTyeY_bHSkTCpCHMSMSxosLjVs4K1Zwq4l0GfZ8UOyFC5jShFrjZHQRvvuHqm_lRugww507bFOLRfc0oJ6zhMxsvU105y0n7kR2m5SePqN6WMXZuEZKAWla9sj299M4_LLlsH26r1EQieiPTMx6YTc.ssWWsJloXD-M88O6rEzd4w

**Comment by volumika** [comment]
Oh. They turned off the promotion. I didn't look further, I apologize for this post.

**Comment by brendeni1** [comment]
Yep... Appears as so. It's too bad.
